aliases:
    - &python_settings
        types: [python]
        exclude: >
            (?x)^(
              .+/migrations/.+|
            )$
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
            -   id: trailing-whitespace
                exclude: ^tests/.*/fixtures/.*
                args: [--markdown-linebreak-ext=md]
            -   id: end-of-file-fixer
                files: '^.*\.(py|mjml|js|jsx|tf|tfvars|conf)$'
            -   id: debug-statements
            -   id: file-contents-sorter
                files: "^requirements(-test)?.in$"

    -   repo: https://github.com/psf/black
        rev: stable
        hooks:
            -   <<: *python_settings
                id: black

    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.8
        hooks:
            -   <<: *python_settings
                id: flake8

    -   repo: https://github.com/asottile/seed-isort-config
        rev: v2.1.1
        hooks:
            -   id: seed-isort-config

    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
            -   <<: *python_settings
                id: isort
                additional_dependencies: [toml]

    - repo: https://github.com/prettier/prettier
      rev: 1.19.1
      hooks:
          - id: prettier
            files: 'frontend/.*\.(js|jsx|ts|tsx)$'

    - repo: local
      hooks:
          - id: eslint
            name: eslint
            types: [file]
            files: 'frontend/.*\.(js|jsx|ts|tsx)$'
            entry: bash -c 'cd frontend && yarn precommit-lint "$@"'
            language: system
